apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-chtoqrbc
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-chtoqrbc:b3747cec14707437ec5eec9636281a18baa6098f@sha256:5ec2694645923bd74459c9145cfb58e24821fd34f2d2bdf9295099cfdebb45a3
          name: container-image
